config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :groups, shallow: true do
    member do
      resources :hits, shallow: true do
        member do
          resources :videos
        end
      end
    end
  end

  root :to => 'groups#index'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :group
  has_many :hits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :hits
  has_many :albums
end

app/models/hit.rb
class Hit < ApplicationRecord
  belongs_to :group
  has_many :videos
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :hit
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @data = Group.all
  end

  def show
    @g = Group.find(params[:id])
    @hits = @g.hits
    @albums = @g.albums
  end
end

app/controllers/hits_controller.rb
class HitsController < ApplicationController
  def show
    @h = Hit.find params[:id]
    @g = @h.group
    @videos = @h.videos
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @v = Video.find(params[:id])
    @h = @v.hit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
<div class="page">
  <div class="page__content-wrapper">
    <% @data.each do |g| %>
      <%= link_to g, class: 'page__group-link' do %>
        <div class="page__group-link-img" style="background-image: url('<%= g.image %>')"></div>
        <h1 class="page__group-title"><%= g.name %></h1>
      <% end %>
  <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="page">
  <!-- <img class="page__bg" src="" %> -->
  <div class="page__bg"
       style="background-image: url('<%= @g.image %>');"></div>
  <div class="page__content-wrapper">
    <header class="page__header">
      <%= link_to 'Home', groups_path, class: 'page__home-link' %>
    </header>
    <article class="page__info-cont">
      <h1 class="page__info-title"><%= @g.name %></h1>
      <div class="page__text-info-wrapper">
        <section class="page__info-bio">
          <div class="page__info-bio-row">
            <p class="page__bio-row-title">Year:</p>
            <p class="page__bio-row-text"><%= @g.year %></p>
          </div>
          <div class="page__info-bio-row">
            <p class="page__bio-row-title">Info: </p>
            <p class="page__bio-row-text"><%= @g.info %></p>
          </div>
          <div class="page__info-bio-row">
            <p class="page__bio-row-title">Members: </p>
            <p class="page__bio-row-text"><%= @g.members %></p>
          </div>
        </section>
        <aside class="page__additional-info-wrapper">
          <section class="page__additional-info-section">
            <h2 class="page__additional-info-section-title">Hits</h2>
            <ul class="page__additional-info-section-list">
              <% @hits.each do |h| %>
                  <li class="page__additional-info-section-item"><%= link_to h.name, h %></li>
              <% end %>
            </ul>
          </section>
          <section class="page__additional-info-section">
            <h2 class="page__additional-info-section-title">Albums</h2>
            <ul class="page__additional-info-section-list">
              <% @albums.each do |a| %>
                  <li class="page__additional-info-section-item page__additional-info-section-item--with-icon">
                    <div class="page__additional-info-section-item-img" style="background-image: url('<%= a.cover %>')"></div>
                    <div class="page__additional-info-section-item-content-wrapper">
                      <p class="page__additional-info-section-item-content-text"><%= a.title %></p>
                      <p class="page__additional-info-section-item-content-text"><%= a.year %></p>
                    </div>
                  </li>
              <% end %>
            </ul>
          </section>
        </aside>
      </div>
    </article>
  </div>
</div>

app/views/hits/show.html.erb
<%= link_to @g.name, @g %>
<p><%= @h.id %></p>
<p><%= @h.name %></p>
<p><%= @h.year %></p>
<p><%= @h.album %></p>
<p>Videos:</p>
<% @videos.each do |h| %>
    <p><%= link_to "Video #{h.id}", h %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Heebo:300,400,500,700&amp;subset=hebrew" rel="stylesheet">
    <title>KpopInfo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/videos/show.html.erb
<%= link_to @h.name, @h %>
<p>Views: <%= @v.views %></p>
<a target="_blank" href="<%= @v.link %>">Watch on YouTube</a>